### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Alycee1993** [kodi1/tvh_rec#1]
i added this via hacs  when restart i have no sensor in my list and in logs i get this 

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 419, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/tvh_rec/sensor.py", line 121, in state
    return str(self._data['count'])
KeyError: 'count'

any ideas

**Comment by kodi1** [comment]
Can you try to run sensor standalone:
`python sensor.py <user> <pass> http://<tvheadend_ip_or_hostname>:9981`

**Comment by JhonnyMnemonic320** [comment]
Hi, this components is also not working for me.

running the sensor with: 
```
python sensor.py <user> <pass> http://<tvheadend_ip_or_hostname>:9981
```
I get this:

```
Traceback (most recent call last):
  File "sensor.py", line 53, in <module>
    d = fetch_data(requests.auth.HTTPDigestAuth(sys.argv[1], sys.argv[2]), sys.argv[3], 3)
  File "sensor.py", line 40, in fetch_data
    'episode_disp': e['episode_disp'],
KeyError: 'episode_disp'
```

EDIT: I'm running: - home-assistant 105.4 - Tvheadend 4.2.4-dmo1~bpo9+1~rpt1

**Comment by kodi1** [comment]
#2

**Comment by Ivanverdonck** [comment]
Hi there,

still have the issue:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 506, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/tvh_rec/sensor.py", line 124, in state
    return str(self._data['count'])
KeyError: 'count'
