### ISSUE TITLE
The sensor no longer works.

### ISSUE THREAD

**Issue by 01815** [kodi1/tvh_rec#13]
Hello,
unfortunately the sensor no longer works. The entity is no longer available to me.
![2024-09-11 09_21_10-Window](https://github.com/user-attachments/assets/aeaf6448-2a6e-4723-b61e-9c75022bab18)
![2024-09-11 09_22_01-Window](https://github.com/user-attachments/assets/5a559521-310d-4b89-9f9a-dc299abc38c3)

**Comment by ronnyadam** [comment]
Same thing for me. I just set up the integration, the sensor was available correctly. After a few weeks, it was no longer available as previously described

**Comment by disconn3ct** [comment]
Disclaimer, this is an initial setup so it might be incorrectly configured:
https://github.com/kodi1/tvh_rec/blob/master/custom_components/tvh_rec/sensor.py#L121
```
2025-09-10 08:57:43.000 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.tvheadend for domain sensor with platform tvh_rec
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
 ^^^^^^^^^^
  File "/config/custom_components/tvh_rec/sensor.py", line 121, in state
    return str(self._data['count'])
               ~~~~~~~~~~^^^^^^^^^
KeyError: 'count'
```
Config:
```
- platform: tvh_rec
  name: TVHeadend
  username: hassio
  password: !secret tvh_pass
  url: http://1.2.3.4:9981
  scan_interval: 600
  count: 12
```
Curl from HA to tvh returns the redirect as expected.
